### ISSUE TITLE
version bump gtk

### ISSUE THREAD

**Issue by pmiess** [0install/0install.de-feeds#15]
I would like to use pygtk for a package of diffuse.
 I think pygtk is incompatible with the available gtk+ version for windows.
The current version of gtk+ is 2.24, and the version of pygtk is 2.24

a windows build of gtk+ can be found here
http://ftp.gnome.org/pub/GNOME/binaries/win32/gtk+/2.24/gtk+-bundle_2.24.10-20120208_win32.zip

**Comment by bastianeicher** [comment]
I have just updated the GTK feed. You can track the pull request [here](/0install/repo.roscidus.com/pull/39/commits/750e950a544ce95b6fe2e84b0a52690a9aa628a9).

**Comment by bastianeicher** [comment]
The underlying issue should be solved now through: 0install/repo.roscidus.com#40
