### ISSUE TITLE
cant run ZeroPublish

### ISSUE THREAD

**Issue by pmiess** [0install/0install.de-feeds#21]
On a new VM attempting to run 0publish  posts the following error 
 

> Failed to download https://downloads.sourceforge.net/project/zero-install/0install/2.11/0install-Windows-2.11.zip.
>         The underlying connection was closed: An unexpected error occurred on a send.
>         Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
>         An existing connection was forcibly closed by the remote host
> 
> Unable to download secondary solver failed
Note that its not a general network problem since I am able to manually 
https://svwh.dl.sourceforge.net/project/zero-install/0install/2.11/0install-Windows-2.11.zip
from 0installs sourceforge files download page

**Comment by bastianeicher** [comment]
Hi @pmiess,

thanks for reporting this issue.

There seem to be two distinct problems occurring here:
1. The regular backtracking solver is failing to resolve the dependencies, which shouldn't happen for 0publish.
2. The more advanced SAT solver cannot be downloaded.

To help me reproduce this, could you provide me with the following information?
- The exact command-line you used to run `0install`.
- The output of `0install --version`.
- The Windows version (including build number if Windows 10) in the VM.

Regards
Bastian

**Comment by pmiess** [comment]
C:\Users\IEUser>0install run http://0install.de/feeds/ZeroInstall_Tools.xml
Running external solver...
[                    ] Downloading https://downloads.sourceforge.net/project/zer
o-install/0install/2.11/0install-Windows-2.11.zip...
[                    ] Web error
Failed to download https://downloads.sourceforge.net/project/zero-install/0insta
ll/2.11/0install-Windows-2.11.zip.
        The underlying connection was closed: An unexpected error occurred on a
send.
        Unable to read data from the transport connection: An existing connectio
n was forcibly closed by the remote host.
        An existing connection was forcibly closed by the remote host
Downloading http://roscidus.com/0mirror/archive/https/downloads.sourceforge.net/
project%23zero-install%230install%232.11%230install-Windows-2.11.zip...
[                    ] Web error
[                    ] Web error
Unable to download secondary solver failed
No solution found

Zero Install Command CLI 2.14.7
Copyright Bastian Eicher et al.
This program comes with ABSOLUTELY NO WARRANTY, to the extent permitted by law.
You may redistribute copies of this program under the terms of the GNU Lesser Ge
neral Public License.

Windows 7 Enterprices
Version 6.1 Build 7601: Service Pack 1

**Comment by pmiess** [comment]
Installing all the required windows updates and rebooting fixed it

**Comment by bastianeicher** [comment]
Thanks for the feedback.

I'm guessing the resolution of the issue may have been related to a .NET update that added support for newer TLS versions.

I will see if I can add a check to a future version of 0install that shows a warning if such an update is missing.
