### ISSUE TITLE
pycharm required java 11

### ISSUE THREAD

**Issue by pmiess** [0install/0install.de-feeds#29]
When I tried to update to the latests version of pycharm the software said it required java 11, but java 8 was selected
I tried to select java 11 but it was not listed in the options for windows 64 bit

**Comment by bastianeicher** [comment]
Thanks for reporting this issue.

JetBrains IDEs up to 2020.2.x supported Java 8.x, which is the latest version for which Oracle released free JRE builds for Windows.
I've updated the JetBrains IDE feeds in e5c68ed9b25a5e847d25faff3be228f687e44815 to use OpenJDK instead, which provides provides Java 9-14 builds for Windows.

**Comment by pmiess** [comment]
works for me :)
Thanks for the fix
